### ISSUE TITLE
Looking for people who can help make my code better

### ISSUE THREAD

**Issue by williambl** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#16]
It's a bit spaghetti-like right now.

**Comment by Valiec** [comment]
I've forked it and added some new features. I'll try to clean it up as I do so.

**Comment by williambl** [comment]
:D thx!

**Comment by williambl** [comment]
Make sure that you keep up-to-date with master branch though. I'm adding a lot of features very fast, and many of them involve rewriting large sections of code...
