### ISSUE TITLE
Getting info from .json

### ISSUE THREAD

**Issue by williambl** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#2]
Could anyone help getting the version information & download link from the .json?

**Comment by LewisTehMinerz** [comment]
Possible in Java, not sure in Python. Maybe you should switch languages

**Comment by williambl** [comment]
I know it's possible, there is a JSON module, it's just that I have no idea
how to use it XD

**Comment by LewisTehMinerz** [comment]
Will do on Java version.

**Comment by williambl** [comment]
Done!
