### ISSUE TITLE
Split code up into multiple files

### ISSUE THREAD

**Issue by williambl** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#23]
When I tried to do it, it threw errors :/

**Comment by Valiec** [comment]
What exactly do you mean by multiple sections? Multiple Python files, organizing it within the same file, or something else entirely?

**Comment by williambl** [comment]
Sorry, should have made it more clear. I meant multiple files.

**Comment by Valiec** [comment]
Hello again, I was busy with EndPlus development for some time there, but I'm back now. I've split the source into multiple files. Since this is a very large change, I am pushing it as a new branch.

**Comment by williambl** [comment]
Thanks! I'll check it out.

**Comment by Valiec** [comment]
Apparently it didn't push right. I'll have it up in a bit.

**Comment by williambl** [comment]
Thanks.
