### ISSUE TITLE
Support multiple mc installs

### ISSUE THREAD

**Issue by williambl** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#26]
Should be easy enough.

**Comment by Valiec** [comment]
I've started working on this. I've got adding new instances somewhat working (switching, removing, listing all instances, etc. aren't done yet).

**Comment by williambl** [comment]
Thanks.

**Comment by Valiec** [comment]
I've mostly finished this feature now. It's on the "instances" branch.

Note: The config.json has been changed and is not backward compatible with pre-1.2 config.jsons.

**Comment by williambl** [comment]
Maybe we should make it 2.0 then, if it's not backwards compatible with old JSONs.

**Comment by Valiec** [comment]
Yes, that sounds like a good idea.
