### ISSUE TITLE
Branch 2.1GUI, file CMAN_util.py, line 34 is broken

### ISSUE THREAD

**Issue by williambl** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#33]
Won't work no matter what I try. I'm trying to make the label called output change its content.

**Comment by Valiec** [comment]
If you mean the exception in Tkinter callback, "output" not defined error, it is because output is defined in CMAN.py, which is not imported in CMAN_util.py

I'd suggest splitting the GUI stuff into another file called CMAN_gui.py. In fact, I'll try to do that and see if it works.

**Comment by Valiec** [comment]
Since this issue is fixed, and GitHub won't autoclose it until this is merged into master, but I don't think this issue needs to stay open that long, I'm closing it manually.

Closing.
