### ISSUE TITLE
Make version selectable by user

### ISSUE THREAD

**Issue by Valiec** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#41]
It doesn't seem you can select which version you want, if there are multiple compatible versions.

**Comment by Valiec** [comment]
Nevermind, It just wasn't documented. I figured it out. Changing issue to be about allowing you to select which version you want.

**Comment by williambl** [comment]
Should the version be selectable in the GUI? I think that most of the time, you would just want the most recent compatible version - if you want another, you can do it in the terminal. What do you think?

**Comment by williambl** [comment]
Closing this, as you can now select it in terminal.
