### ISSUE TITLE
Unnecessary mod update notices

### ISSUE THREAD

**Issue by Valiec** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#43]
When a mod is downloaded but not installed (e.g. because it is incompatible combined with #42), CMAN will print a message to the console saying that the mods have updates available, listing the "current version" and the "latest version" as the same version.

**Comment by williambl** [comment]
I could reproduce this before, but can't now - could you show me how?

**Comment by Valiec** [comment]
This bug is partly a side effect of #42, so with it fixed, this will be harder to reproduce.

I can't seem to reproduce it with #42 fixed (except for cases involving leftover data from before #42 was fixed).

**Comment by williambl** [comment]
I'll close it now you've confirmed that it's fixed.
