### ISSUE TITLE
Find out how to install base mods

### ISSUE THREAD

**Issue by williambl** [Comprehensive-Minecraft-Archive-Network/CMAN-Python#9]
Argh this will be hard...

**Comment by MMC-translator** [comment]
What do you mean by base mods?

**Comment by williambl** [comment]
Things which modify minecraft.jar itself.

**Comment by peterix** [comment]
There are almost none.

**Comment by williambl** [comment]
check modlist.mcf.li. There aren't many, but more than you would think.

**Comment by peterix** [comment]
You need to merge the zip files.

Take minecraft the jar and a list of all other zip/jar stuff you want to add: [minecraft.jar, a.jar, b.jar, c.zip, ..., z.zip]

Create an empty final zip/jar file.
1. Take the last file in the list and add all its files to the final jar file, excluding the META-INF folder and any files that are already in the final jar.
2. Remove the file from the list.
3. Continue with the previous file, until there are no more in the list.

**Comment by williambl** [comment]
This makes me remember installing modloader, back when I thought that forge would mess up my saves (no idea why i thought that) XD

thanks for explaining how I should do it in the program
